app_score:
    type:     rest
    resource: AppBundle\Controller\ScoreController

app_game:
    type:     rest
    resource: AppBundle\Controller\GameController

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
