services:
    app.score.manager:
        class: "AppBundle\Manager\ScoreManager"
        arguments: [@doctrine.orm.entity_manager, "AppBundle\Entity\Score", @form.factory]
    app.game.manager:
        class: "AppBundle\Manager\GameManager"
        arguments: [@doctrine.orm.entity_manager, "AppBundle\Entity\Game", @form.factory]